name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  HARBOR_REGISTRY: 210.90.24.172:8080
  HARBOR_PROJECT: camit
  STUDENT_ID: toemsamnob
  IMAGE_NAME: resttemplateserver-sep

  GITOPS_REPO: leeyoungkon/resttemplateserver-sep-gitops
  GITOPS_PATH: overlays/dev
   
jobs:
  build-and-push:
    name: Build & Push to Harbor
    runs-on: self-hosted

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Generate image tag
        id: meta
        shell: pwsh
        run: |
          "tag=${{ github.sha }}" >> $env:GITHUB_OUTPUT

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: false
          sbom: false
          tags: |
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.STUDENT_ID }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.STUDENT_ID }}/${{ env.IMAGE_NAME }}:latest

  update-gitops:
    name: Update GitOps Repo for ArgoCD
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      
      - name: Install kustomize
        shell: pwsh
        run: |
          $version = "v5.7.1"

          Invoke-WebRequest `
            -Uri "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/$version/kustomize_${version}_windows_amd64.zip" `
            -OutFile kustomize.zip

          Expand-Archive kustomize.zip -DestinationPath .

          echo "$PWD" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

          .\kustomize.exe version    

      - name: Update image tag
        shell: pwsh
        run: |
          cd gitops/${{ env.GITOPS_PATH }}

          kustomize edit set image `
            ${{ env.IMAGE_NAME }}=${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.STUDENT_ID }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag }}

      - name: Commit and push GitOps change
        shell: pwsh
        run: |
          cd gitops
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git diff --staged --quiet
          if ($LASTEXITCODE -ne 0) {
            git commit -m "ci: update ${{ env.IMAGE_NAME }} image to ${{ needs.build-and-push.outputs.image_tag }}"
            git push
          }